package backend.entity;

public enum CategorieChatbot {
    ALLERGIES,
    TRAITEMENTS,
    ANTECEDENTS,
    HABITUDES_DE_VIE,
    VACCINATIONS,
    MOTIF_CONSULTATION,
    ACTIVITE_PHYSIQUE,
    SOMMEIL,
    PREVENTION,
    ENVIRONNEMENT,
    SANTE_MENTALE,
    DOULEURS,
    GERIATRIE,
    ALIMENTATION


}